### ISSUE TITLE
[META] Update the GitHub repo to make use of the newest features

### ISSUE THREAD

**Issue by Unknown6656** [Unknown6656/AutoIt-Interpreter#191]
- [x] update issue templates
- [x] make bug issue template interactive
- [x] transition to the newer Github project system (https://github.com/users/Unknown6656/projects/2)
- [x] use discussion feature (#194 )
- [x] check why tf the appveyor CD builds are failing (probably missing tests, see #28 ). covered by the following commits:
    - 1b5fe1f6af2d0c353406480247880c8fb89cf6e6
    - 7c88dc72bb79cfdb0be5087dc144a7d05d5f4fe6
    - 93e05f5d386a5d13dbf3e4df3387cc816c0c7156
    - fc93768f4fb9ffa967d6ed5dac565bc70f649f24
    - 95d3204dacbe3ec3448368c8fcef4885fd80120a
    - 8a14e443ea780aae0998a5504aed733eedb6fed1
    - 4592ebd76d900b230aa227fa0ec2233d46cf86f2
    - b45f28a975dc66fd8e2685e43bb564be8839c799
    - e73fb212c03224c0c8f3c7daaea462c6b4a268bf
    - c5c0ae9b2ca725666798c8849ecef7de50580e0b
- [x] split repo (see https://github.com/Unknown6656/AutoIt-Interpreter-old/, moved with e96dab771e4221cb4fb7ea9c09b5e3f3552edbe2)
