### ISSUE TITLE
[BUG] Line processing mode not working

### ISSUE THREAD

**Issue by Unknown6656** [Unknown6656/AutoIt-Interpreter#193]
### TODOs
- [x] fix: interpreter not executing any line (72a748c8d84a97e47f23e0c2c64c13e602dd7b91)
- [x] fix: interpreter not throwing errors (92df3368c93f6a14cf4f59be11aa4ef85ab36069, #197 )
- [x] fix: telemetry not being printed (fc8e83b32164422fe0cbcc8b641fbb42ebe0d778)

---------

### Bug Description

When executing any (valid) AutoIt3-statement in "line processing mode", no output is printed to the CLI.

### Steps to reproduce the Bug

1. Open shell
2. Execute `autoit3 -ml "ConsoleWrite(@OSVERSION)"`
3. No ouput

### Expected Behavior

Expected output:
```shell
> autoit3 -ml "ConsoleWrite(@OSVERSION)"
WIN32_NT
```

### Operating System Type

Windows

### Operating System Architecture

x64

### Operating System Descriptor

Microsoft Windows [Version 10.0.22631.3296]

### AutoIt Interpreter Version

```text
+-----------------+
|     .=%B@XOE+.  |
|    . + XOX+=o   |   AUTOIT3 INTERPRETER
|     *oo+B.o..   |     Written by Unknown6656, 2018 - 2024
|    ..oo..o..    |
|        S..      |   https://github.com/Unknown6656/AutoIt-Interpreter/
|                 |
|                 |   Version 0.12.2279.8640, 16d8df1612f3f5baf4d886fc0cceee0335e6800f
|                 |   750C38797612057E030072B25778CA0D4147BD558C909A89D54A5214F013F154
|                 |
+-----------------+
```

**Comment by Unknown6656** [comment]
issue mostly resolved. question: should the last result value also be printed when in telemetry/timings/verbose mode?
